## Copyright 2021 Paingha Joe Alagoa. All rights reserved.
## Use of this source code is governed by a BSD-style
## license that can be found in the LICENSE file.

FROM envoyproxy/envoy-alpine:v1.14-latest
COPY envoy.yaml /etc/envoy/envoy.yaml